// Generated by CoffeeScript 1.6.3
(function() {
  var AWS, config;

  AWS = require('aws-sdk');

  config = api.configData.s3;

  AWS.config.update({
    accessKeyId: config.access_key_id,
    secretAccessKey: config.secret_access_key
  });

  exports.aws_helper = function(api, next) {
    api.aws_helper = {
      upload: function(params, callback) {
        var s3,
          _this = this;
        config = api.configData.s3;
        if (!config.use_private_urls) {
          params.ACL = 'public-read';
        }
        s3 = new AWS.S3();
        s3.client.putObject(params, function(error, result) {
          var url;
          if (error) {
            if (callback) {
              callback(error, void 0);
              return false;
            } else {
              throw error;
            }
          } else {
            if (config.use_private_urls) {
              delete params.Body;
              delete params.ContentLength;
              delete params.Metadata;
              params.Expires = config.urls_expire_after || 900;
              url = s3.getSignedUrl('getObject', params);
              if (callback) {
                callback(void 0, url);
              }
            } else {
              if (callback) {
                callback(void 0, "http://s3.amazonaws.com/" + config.bucket_name + "/" + params.Key);
              }
            }
            true;
          }
          return true;
        });
        return true;
      }
    };
    return next();
  };

  modules.exports = exports;

}).call(this);
