// Generated by CoffeeScript 1.6.3
(function() {
  var exports;

  exports = {
    clientsIndex: {
      name: "clientsIndex",
      description: "Shows the list of existing clients",
      inputs: {
        required: [],
        optional: []
      },
      authenticated: false,
      outputExample: {},
      version: 1.0,
      run: function(api, connection, next) {
        return api.clients.find(function(error, clients) {
          connection.error = error;
          connection.response = {
            clients: clients
          };
          return next(connection, false);
        });
      }
    },
    clientsCreate: {
      name: "clientsCreate",
      description: "Adds a new client",
      inputs: {
        required: ["name"],
        optional: ["redirectURL"]
      },
      authenticated: false,
      outputExample: {},
      version: 1.0,
      run: function(api, connection, next) {
        return api.clients.create({
          name: connection.params.name,
          redirectURL: connection.params.redirectURL
        }, function(error, client) {
          connection.error = error;
          connection.response = {
            client: client
          };
          return next(connection, false);
        });
      }
    }
  };

  module.exports = exports;

}).call(this);
